apiVersion: projectcontour.io/v1
kind: HTTPProxy
metadata:
  name: todo-httpproxy
  namespace: todo-prod
spec:
  virtualhost:
    fqdn: todo.local
    tls:
      secretName: todo-tls
  routes:
    - services:
        - name: todo-service
          port: 80
